### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by joostf** [nickrttn/web-app-from-scratch#12]
Are you sure you want to run strict mode on the global scope?

https://github.com/nickrttn/web-app-from-scratch/blob/cf1ccb8bb369015e593c8aaa0686b14664a5b8fe/spa/assets/app.js#L1

**Comment by joostf** [comment]
https://github.com/nickrttn/web-app-from-scratch/blob/cf1ccb8bb369015e593c8aaa0686b14664a5b8fe/spa/assets/app.js#L1

**Comment by nickrttn** [comment]
I'm sure I don't. In this case I'm not concatenating external scripts to my own application, but that might well change in the future. As ES2015 classes are strict mode by default (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), I've added `'use strict'` to the IIFE that instantiates the app when the page has loaded.
