### ISSUE TITLE
Consider using a defer/async attribute 

### ISSUE THREAD

**Issue by joostf** [nickrttn/web-app-from-scratch#6]
Instead of placing script tags at the bottom of your body, you can defer or async script and place it in the head section of your document.

https://github.com/nickrttn/web-app-from-scratch/blob/10016b7cd69ff4dcdf291fdb7b7905af4e0993ca/spa/index.html#L24

**Comment by nickrttn** [comment]
defer *or* async, or defer *and* async? There seems to be a lot of discussion about this around the web, most of which dates from around 2012. The most read conclusion of the debate is: including a script tag before the body is the easiest way to ensure the DOM is parsed and painted before your JS is parsed and executed.
