### ISSUE TITLE
Ternary operator (maybe)

### ISSUE THREAD

**Issue by lhafkamp** [nickrttn/web-app-from-scratch#8]
Instead of:

![screen shot 2017-02-09 at 18 52 01](https://cloud.githubusercontent.com/assets/14187210/22795966/ea3c8f2e-eef8-11e6-9cc4-c6d64f51d2ae.png)

You could use the ternary operator to fit it all on "one" line:
this.sections.forEach(section => route.includes(section.id) ? section.classList.remove('visually-hidden') : section.classList.add('visually-hidden'));

Its a bit long though so I'm not sure if its worth the code reduction because it becomes less readable ¯\_(ツ)_/¯

**Comment by nickrttn** [comment]
Readability is exactly why I didn't do that :)
