### ISSUE TITLE
Don't use lorem ipsum

### ISSUE THREAD

**Issue by joostf** [nickrttn/web-app-from-scratch#9]
Fons will be mad!

https://github.com/nickrttn/web-app-from-scratch/blob/cf1ccb8bb369015e593c8aaa0686b14664a5b8fe/spa/index.html#L20

**Comment by nickrttn** [comment]
I'll gather some real content.

**Comment by nickrttn** [comment]
fixed in commit 98160c6703277c60e9e7fddce1458b8cdddf59a1
